
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-app
spec:
  selector:
    matchLabels:
      app: simple-node-app
  template:
    metadata:
      labels:
        app: simple-node-app
    spec:
      containers:
      - name: simple-node-app
        # use an env variable so we can replace it
        image: ${IMAGE_NAME}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: simple-node-app
spec:
  type: LoadBalancer
  selector:
    app: simple-node-app
  ports:
  - port: 80
    targetPort: 3000
